# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0745da66c50c116911418b05bda9c7957304e8c1a2622085dd9bcb69eae040a052148e5e643e14fd75af646e347878dee895e7e80d91476524a396bcb6f27753

test:
  secret_key_base: f20b314600e8d5baab620d86e10857ca501d4e65755adbc5b021bf2919ee4eb9ed4e0b1005e82d0accbd330dcfdbe059b6c967d901fa0bb4caedb0344183670c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
